version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-cli: circleci/aws-cli@3.1.4

jobs:
  continuous-integration:
    docker:
      - image: cimg/base:stable
    resource_class: shreyash/txtclssrunner
    steps:
      - checkout
      - aws-cli/setup
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker Image
          command: |
            docker build -t textclass .

      - run:
          name: Authenticate to AWS ECR
          command: |
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 820242917185.dkr.ecr.ap-south-1.amazonaws.com

      - run:
          name: Tag and Push Docker Image to ECR
          command: |
            docker tag textclass:latest 820242917185.dkr.ecr.ap-south-1.amazonaws.com/textclass:latest
            docker push 820242917185.dkr.ecr.ap-south-1.amazonaws.com/textclass:latest

  continuous-delivery:
    docker:
      - image: cimg/base:stable
    resource_class: shreyash/txtclssrunner
    steps:
      - checkout
      - aws-cli/setup

      - run:
          name: Authenticate to AWS ECR
          command: |
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 820242917185.dkr.ecr.ap-south-1.amazonaws.com

      - run:
          name: Pull and Run Docker Image
          command: |
            docker pull 820242917185.dkr.ecr.ap-south-1.amazonaws.com/textclass:latest
            docker run -d -p 8080:8080 820242917185.dkr.ecr.ap-south-1.amazonaws.com/textclass:latest

workflows:
  CICD:
    jobs:
      - continuous-integration
      - continuous-delivery:
          requires:
            - continuous-integration
