version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4

jobs:
  continuous-integration:
    machine: true
    steps:
      - checkout
      
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set region $AWS_REGION
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

      - run:
          name: Login to AWS ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - run:
          name: Build Docker image
          command: |
            docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/demo:latest .

      - run:
          name: Push Docker image to ECR
          command: |
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/demo:latest

  continuous-delivery:
    machine: true
    steps:
      - checkout

      - run:
          name: Login to AWS ECR
          command: |
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 820242917185.dkr.ecr.ap-south-1.amazonaws.com

      - run:
          name: Pull latest Docker image
          command: |
            docker pull 820242917185.dkr.ecr.ap-south-1.amazonaws.com/shreyash/sentiment_analysis:latest

      - run:
          name: Run Docker container
          command: |
            docker run -d -p 8080:8080 820242917185.dkr.ecr.ap-south-1.amazonaws.com/shreyash/sentiment_analysis:latest

workflows:
  CICD:
    jobs:
      - continuous-integration
      - continuous-delivery:
          requires:
            - continuous-integration
